# Generated by Django 2.1 on 2018-09-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='year',
            field=models.IntegerField(default=2018),
        ),
    ]
