# Generated by Django 2.1 on 2018-09-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0002_auto_20180905_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchup',
            name='week',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='year',
        ),
    ]
