# Generated by Django 2.1 on 2018-09-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1999)),
                ('week', models.IntegerField(default=0)),
                ('b1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b1', to='players.PlayerWeek')),
                ('b2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2', to='players.PlayerWeek')),
                ('b3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b3', to='players.PlayerWeek')),
                ('b4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b4', to='players.PlayerWeek')),
                ('b5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b5', to='players.PlayerWeek')),
                ('b6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b6', to='players.PlayerWeek')),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst', to='players.PlayerWeek')),
                ('flex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flex', to='players.PlayerWeek')),
                ('ir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ir', to='players.PlayerWeek')),
                ('k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k', to='players.PlayerWeek')),
                ('qb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qb', to='players.PlayerWeek')),
                ('rb1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rb1', to='players.PlayerWeek')),
                ('rb2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rb2', to='players.PlayerWeek')),
                ('te', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='te', to='players.PlayerWeek')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('ties', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='lineup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.Team'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='wr1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wr1', to='players.PlayerWeek'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='wr2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wr2', to='players.PlayerWeek'),
        ),
    ]
