# Generated by Django 2.1 on 2018-09-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineup',
            name='b1',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='b2',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='b3',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='b4',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='b5',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='b6',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='dst',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='flex',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='ir',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='k',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='qb',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='rb1',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='rb2',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='te',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='wr1',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='wr2',
        ),
        migrations.AddField(
            model_name='lineup',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='year',
            field=models.IntegerField(default=2018),
        ),
    ]
