# Generated by Django 2.1 on 2018-09-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20180904_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineupPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
            ],
        ),
    ]
