# Generated by Django 2.1.3 on 2018-11-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20180907_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFLTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('conference', models.CharField(max_length=3)),
                ('division', models.CharField(max_length=5)),
            ],
        ),
    ]
