version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_CONFIG_MAX_CONNECTIONS: 10
            POSTGRES_CONFIG_shared_buffers: 512MB
        volumes:
            - db-data:/var/lib/postgresql/data

    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db

volumes:
    db-data:
