# Generated by Django 2.1 on 2018-09-03 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1999)),
                ('week', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1999)),
                ('week', models.IntegerField(default=0)),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='stats.Lineup')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='stats.Lineup')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1999)),
                ('week', models.IntegerField(default=0)),
                ('points', models.FloatField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stats.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('ties', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='lineup',
            name='b1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b1', to='stats.PlayerPoints'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='b2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2', to='stats.PlayerPoints'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='b3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b3', to='stats.PlayerPoints'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='b4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b4', to='stats.PlayerPoints'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='b5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b5', to='stats.PlayerPoints'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='b6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b6', to='stats.PlayerPoints'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='dst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst', to='stats.PlayerPoints'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='flex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flex', to='stats.PlayerPoints'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='ir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ir', to='stats.PlayerPoints'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='k',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k', to='stats.PlayerPoints'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='qb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qb', to='stats.PlayerPoints'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='rb1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rb1', to='stats.PlayerPoints'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='rb2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rb2', to='stats.PlayerPoints'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='te',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='te', to='stats.PlayerPoints'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stats.Team'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='wr1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wr1', to='stats.PlayerPoints'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='wr2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wr2', to='stats.PlayerPoints'),
        ),
    ]
