# Generated by Django 2.1 on 2018-09-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1999)),
                ('week', models.IntegerField(default=0)),
                ('points', models.FloatField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='players.Player')),
            ],
        ),
    ]
