# Generated by Django 2.1 on 2018-09-04 18:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20180904_1841'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerweek',
            name='lineup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teams.Lineup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerweek',
            name='lineup_position',
            field=models.CharField(default=None, null = True, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerweek',
            name='year',
            field=models.IntegerField(default=2018),
        ),
    ]
