# Generated by Django 2.1 on 2018-09-04 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_lineupposition'),
        ('players', '0002_auto_20180904_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerweek',
            name='lineup',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='teams.Lineup', null=True),
        ),
        migrations.AlterField(
            model_name='playerweek',
            name='lineup_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.LineupPosition'),
        ),
    ]
