# Generated by Django 2.1 on 2018-09-04 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20180904_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerweek',
            name='lineup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='teams.Lineup'),
        ),
        migrations.AlterField(
            model_name='playerweek',
            name='lineup_position',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='teams.LineupPosition'),
        ),
    ]
