# Generated by Django 2.1 on 2018-09-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20180904_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerweek',
            name='lineup_position',
        ),
    ]
