# Generated by Django 2.1 on 2018-09-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_remove_playerweek_lineup_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerweek',
            name='lineup',
        ),
    ]
