# Generated by Django 2.1 on 2018-09-04 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_lineupposition'),
        ('players', '0007_remove_playerweek_lineup'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerweek',
            name='lineup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='teams.Lineup'),
        ),
        migrations.AddField(
            model_name='playerweek',
            name='lineup_position',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='teams.LineupPosition'),
        ),
    ]
