# Generated by Django 2.1 on 2018-09-05 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20180904_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerweek',
            name='lineup',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='teams.Lineup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerweek',
            name='lineup_position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='teams.LineupPosition'),
            preserve_default=False,
        ),
    ]
