# Generated by Django 2.1.3 on 2018-11-08 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_nflteam'),
        ('players', '0010_player_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerweek',
            name='nfl_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teams.NFLTeam'),
        ),
    ]
