# Generated by Django 2.1.3 on 2018-11-12 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_nflteam'),
        ('players', '0011_playerweek_nfl_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teams.NFLTeam'),
        ),
    ]
